### ISSUE TITLE
4 ROI selection produces 12 TIFF images

### ISSUE THREAD

**Issue by gracemcl** [loganfred/gladlab-ip#1]
The TIFF images appear to be duplicates.

It could be related to a click-order issue with multiple exports. See attached export.json.

[export.json.zip](https://github.com/loganfred/gladlab-ip/files/7589799/export.json.zip)

**Comment by loganfred** [comment]
I'll try to explain bugs (as I understand them) when appropriate since I think it is illustrative for a project like this.

This is caused by a bug in the javascript code.

```javascript
function onHyphaePick(b64_hyphae, onPathClose) {
    hyphae.src = 'data:image/png;base64,' + b64_hyphae;
    hyphae.onload = () => {
        let imgInstance = new fabric.Image(hyphae);
        canvas.clear();
        canvas.setBackgroundImage(imgInstance, canvas.renderAll.bind(canvas));
        onDrawStart();
        canvas.on('path:created', (d) => onPathClose(d));
    }
}
```

The last line there is the culprit. 

```javascript
canvas.on('path:created', (d) => onPathClose(d));
```

Apparently the `on()` function will append callbacks when called repeatedly. So each time this `onHyphaePick()` function is called, the core processing event that happens in `onPathClose()` will be done another time.

This explains why each time a new image was rendered after clicking the `update` button, the number of paths created from a single lasso would be an increased multiple.

The fix was to simply move the callback registration line outside the function so it only runs once.
