### ISSUE TITLE
saved tiffs

### ISSUE THREAD

**Issue by gracemcl** [loganfred/gladlab-ip#7]
[Archive.zip](https://github.com/loganfred/gladlab-ip/files/8027346/Archive.zip)
saved tiffs lead to the attached error when opening with preview. Opening in imagej and then saving as a tiff from there gets rid of the error. 
before.tiff is what comes out of this, after.tiff is from imagej

![Screen Shot 2022-02-08 at 3 48 45 PM](https://user-images.githubusercontent.com/57114885/153073111-9be1ac25-2d29-485b-90cb-bfdcf81e2771.png)

**Comment by loganfred** [comment]
It looks like the root cause of this issue comes from the following line:

```python
hypha = stack.punchMask(mask, roi, crop=True)
```
Tracing deeper, the following numpy function is unexpectedly returning `float64` rather than the original data type of `uint16`. 

```python
result = np.where(mask, self, self.mean())
```

`self` here is the zstack object which inherits from `ND2Reader` which itself inherits from PIMS `ImageSequence`. `mask` is a `bool` of course, but there is something wonky going on about how these `ImageSequence` objects return pixel data. `self[0].dtype`  is `uint16` but interestingly `self.dtype` is `float64`

The documentation is down for the `ND2Reader` at the moment so the best I can do is force the expected datatype.

```python
result = np.where(mask, self, self.mean()).astype('uint16')
```

Initial inspection suggests that the pixel values are not changed as a result of this workaround.

This is an image of the histograms of the ND2Reader image and the output TIFF image in ImageJ after making the proposed change. (I changed `crop=False` in the first code snippet mentioned in this message in order to produce a TIFF image that was not cropped for better comparison to the source image)

![Screen Shot 2022-02-12 at 11 01 50 AM](https://user-images.githubusercontent.com/24829027/153719168-65cc8afc-233f-4187-9128-919b1f1dd6f0.png)

This is a subtraction of the two images, shown with a lookup table. The cursor is hidden by the screenshot, but the green region is shown to be zero in the toolbar. This is what we would expect if the pixel values were identical.

![Screen Shot 2022-02-12 at 11 07 53 AM](https://user-images.githubusercontent.com/24829027/153719306-87fce02e-4d7f-41e7-a082-2539bc3a15c5.png)

As a pleasant side-effect of this change the images are now able to be opened in the Preview App. I don't have ImageTank, but the fact that preview will open it seems like a good sign. (Of course it is all black since Preview is a little confused about the low contrast and lack of much content in the first several slices)

![Screen Shot 2022-02-12 at 11 24 13 AM](https://user-images.githubusercontent.com/24829027/153719405-fce5d33e-8f3b-4844-8ed0-2d5bddf422de.png)
